### ISSUE TITLE
Error in new commit

### ISSUE THREAD

**Issue by beasttamer01** [PredatorHackerzZ/TG-FileStore#7]
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    from handlers.send_file import send_media_and_reply
  File "/root/FileStoreBot_V3/handlers/send_file.py", line 29
    await message.delete()
    ^
SyntaxError: 'await' outside function

**Comment by PredatorHackerzZ** [comment]
fixed

**Comment by beasttamer01** [comment]
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    from handlers.send_file import send_media_and_reply
  File "/root/FileStoreBot_V3/handlers/send_file.py", line 21
    sent_message = await bot.copy_message(chat_id=user_id, from_chat_id=Config.DB_CHANNEL, message_id=file_id)
               ^
IndentationError: expected an indented block
